In [2]:
import numpy
n = numpy.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [3]:
import cv2

In [16]:
im = cv2.imread('smallgray.png', 0)
im

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [20]:
im = im[0:2, 0:2]

In [21]:
cv2.imwrite('test.png', im)

True

In [23]:
im.shape

(2, 2)

In [25]:
im.T

array([[187, 198],
       [158, 125]], dtype=uint8)

In [30]:
for i in im.flat:
    print(i)

187
158
198
125


In [33]:
from geopy.geocoders import ArcGIS

In [34]:
test = ArcGIS()

In [35]:
test

In [45]:
test = test.geocode('13410 Forest Oaks Dr, Smithville, MO 64089')

In [46]:
test

Location(13410 Forest Oaks Dr, Smithville, Missouri, 64089, (39.33643711766414, -94.56801585902234, 0.0))

In [47]:
test.latitude

39.33643711766414

In [48]:
test.longitude

-94.56801585902234